### ISSUE TITLE
win7x64，按照教程不行，自己尝试配置也不行

### ISSUE THREAD

**Issue by asundust** [forecho/PHPStorm-Config#1]
而且和教程说的目录结构不一样，在option下有个keymap.xml
图片不知道为什么发不出去，
http://ww1.sinaimg.cn/large/702981f5gy1feprokmmdkj20do0e3myt.jpg
http://ww1.sinaimg.cn/large/702981f5gy1feprvbpdkej20cb044wen.jpg

**Comment by forecho** [comment]
抱歉，现在才看到问题。

`在 option下有个 keymap.xml ` 这个不用管。
你直接把文件夹丢到 `\.PhpStorm2017.2\config ` 就可以了，你可能需要做的就是在 PhpStorm 的设置里面修改一下配置信息，如下操作：

![image](https://user-images.githubusercontent.com/1725326/30850010-b36fc1d6-a2d6-11e7-9c19-7aad53bbd862.png)

点击保存。
